### ISSUE TITLE
Apply: ActiveType Models

### ISSUE THREAD

**Issue by JoshBroomberg** [iExperience/ixjourney#2]
- Submission
  - No inherited persistence
  - Validates that all unique questions, as determined by selected programs, have responses. 
  - After create: updates submitted_at on application, creates a submitted event. 
- Active application
  - Inherits from Application
  - validates deactivated_at is not present
- SubmittedApplication _(used in submission model)_
  - inherits from ActiveApplication
  - Validates submitted_at present

**Comment by khanotations** [comment]
I don't think "Active" is the right word.
