### ISSUE TITLE
Apply: interview

### ISSUE THREAD

**Issue by JoshBroomberg** [iExperience/ixjourney#20]
Create the interview system for user. Notionally this means storing an interview link and an interviewed_at time. 

After consideration, I believe it is best that this link is stored on the user and not as a response to a question. This simplifies the display/operation of both the written app and the interview. *This is still open to discussion*. 

- Create User::AsInterviewed model which validates presence + format of interview_link and presence of interviewed_at.
- Create an interviews controller to handle the creation of User::AsInterviewed. Actions:
  - New - displays interview instructions and link input box
  - Create - saves the link and set's interviewed_at (as an after_save call back)

**Comment by khanotations** [comment]
I think this is done
