### ISSUE TITLE
Apply: Controllers

### ISSUE THREAD

**Issue by JoshBroomberg** [iExperience/ixjourney#4]
- ProfileComplete controller
  - create (takes all the new params to create a 'profile complete' user)
- JourneysController
 - new: displays the program choice page. User selects course, session and internship yes/no. Build this off the existing structure in ixstudents.
 - create: creates new journeys based on user choice. Creates between 1 and 2 journeys in this version. Should override old journeys if they are unsubmitted. 
- SubmissionController
 - new: shows all unique questions as determined by programs selected via applications
 - create: creates a submission

**Comment by khanotations** [comment]
`SubmissionsController`

Where is the applications#new page?
